# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servo', '0057_auto_20161014_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair',
            name='confirmation',
            field=models.CharField(default=b'', editable=False, max_length=15),
        ),
    ]
