# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servo', '0059_repair_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair',
            name='status_code',
            field=models.CharField(choices=[(b'AWTP', b'Awaiting Parts'), (b'AWTR', b'Parts Allocated'), (b'BEGR', b'In Repair'), (b'RFPU', b'Ready for Pickup')], default=b'', editable=False, max_length=4),
        ),
    ]
