# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servo', '0060_auto_20161101_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='notes',
            field=models.TextField(blank=True, default='Business hours between 9:00 - 18:00', help_text='Will be shown on print templates', verbose_name='Notes'),
        ),
    ]
